### ISSUE TITLE
Python build error on Windows 10

### ISSUE THREAD

**Issue by Slion** [anssih/finqwerty#14]
I'm trying to build FinQwerty on Windows 10 but it looks like it bugs out trying to use that Python script.

```
Traceback (most recent call last):
  File "C:\Dev\GitHub\finqwerty\finqwerty/../generate_layouts.py", line 319, in <module>
    main()
  File "C:\Dev\GitHub\finqwerty\finqwerty/../generate_layouts.py", line 316, in main
    generate_all_layouts(target_dir=sys.argv[1])
  File "C:\Dev\GitHub\finqwerty\finqwerty/../generate_layouts.py", line 313, in generate_all_layouts
    generate_layouts(layouts=GENERATED_LAYOUTS, target_dir=target_dir)
  File "C:\Dev\GitHub\finqwerty\finqwerty/../generate_layouts.py", line 299, in generate_layouts
    generate_layout(layout, target_dir)
  File "C:\Dev\GitHub\finqwerty\finqwerty/../generate_layouts.py", line 295, in generate_layout
    dst.write(layout.get(ADD, ""))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u017a' in position 197: character maps to <undefined>
```

**Comment by Slion** [comment]
Apparently you need to specify `encoding="utf-8"` when opening the file.
See:
https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

**Comment by anssih** [comment]
Thanks, fixed.
